# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qskos
                                 A QGIS plugin
 Semantic annotation of vector layer features using SKOS vocabularies.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-22
        copyright            : (C) 2024 by Your Name
        email                : your.email@example.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Your Name'
__date__ = '2024-05-22'
__copyright__ = '(C) 2024 by Your Name'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import QgsApplication

from .qskos_provider import qskosProvider

class qskosPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = qskosProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        self.initProcessing()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)

# -------------------------------------
# 👇 ADD THIS FUNCTION FOR COMPATIBILITY
# -------------------------------------
def classFactory(iface):
    """Load qskosPlugin class from file qskos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    return qskosPlugin(iface)