# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qskos
                                 A QGIS plugin
 Semantic annotation of vector layer features using SKOS vocabularies.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Your Name
        email                : your.email@example.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QSettings,
    QTranslator,
    QUrl,
    Qt,
    QTimer,
    pyqtSignal
)
from qgis.PyQt.QtGui import QIcon, QStandardItemModel, QStandardItem
from qgis.PyQt.QtWidgets import (
    QAction,
    QFileDialog,
    QMessageBox,
    QTreeWidgetItem,
    QCheckBox
)
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsField,
    QgsFields,
    QgsVectorFileWriter,
    QgsWkbTypes,
    QgsExpression,
    QgsMapLayer,
    QgsMessageLog,
    Qgis
)
from qgis.gui import QgsMessageBar

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .qskos_dialog import qskosDialog
import os.path
import csv
import tempfile
import urllib.request
import urllib.error
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import SKOS, RDF

class qskos:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'qskos_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&qskos')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # References to UI elements
        self.dlg = None
        self.vocab_layer_combo = None
        self.feature_layer_combo = None
        self.tree_widget = None
        self.bind_button = None

        # Connect to layer events for auto-refresh
        QgsProject.instance().layerWasAdded.connect(self.on_layer_added_removed)
        QgsProject.instance().layerWillBeRemoved.connect(self.on_layer_added_removed)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('qskos', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

def initGui(self):
    """Create the menu entries and toolbar icons inside the QGIS GUI."""

    # 👇 Use QIcon() for no icon — text label will be shown instead
    self.action = QAction(
        QIcon(),  # ← Empty icon → text-only button
        self.tr(u'SKOS Annotation'),
        self.iface.mainWindow()
    )
    self.action.triggered.connect(self.run)
    self.action.setStatusTip(self.tr('Open SKOS Annotation Dialog'))
    self.action.setWhatsThis(self.tr('Open the qskos plugin to annotate features with SKOS vocabularies.'))

    # Add to Plugins menu
    self.iface.addPluginToMenu(self.menu, self.action)
    # Add to toolbar — will show as text button if no icon
    self.iface.addToolBarIcon(self.action)

    # Initialize Processing provider (optional)
    self.initProcessing()

    self.first_start = True

def unload(self):
    """Removes the plugin menu item and icon from QGIS GUI."""
    # 👇 REMOVE ACTION
    self.iface.removePluginMenu(self.tr(u'&qskos'), self.action)
    self.iface.removeToolBarIcon(self.action)
    del self.action

    # Disconnect signals
    QgsProject.instance().layerWasAdded.disconnect(self.on_layer_added_removed)
    QgsProject.instance().layerWillBeRemoved.disconnect(self.on_layer_added_removed)

    # Remove Processing provider
    if self.provider:
        QgsApplication.processingRegistry().removeProvider(self.provider)

    def on_layer_added_removed(self):
        """Slot for layer addition/removal. Uses a timer to avoid reentrancy."""
        QTimer.singleShot(0, self.refresh_layer_dropdowns)

    def refresh_layer_dropdowns(self):
        """Refreshes the layer dropdowns in the UI."""
        if self.dlg is None or not self.dlg.isVisible():
            return

        current_vocab = self.vocab_layer_combo.currentData()
        current_feature = self.feature_layer_combo.currentData()

        self.vocab_layer_combo.clear()
        self.feature_layer_combo.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer:
                # Check for vocabulary layer: delimited text with 'qskos:scheme' property
                if layer.dataProvider().name() == 'delimitedtext' and \
                   layer.customProperty('qskos:scheme'):
                    self.vocab_layer_combo.addItem(layer.name(), layer.id())

                # Check for feature layer: has geometry and is not delimited text
                elif layer.geometryType() != QgsWkbTypes.NullGeometry:
                    self.feature_layer_combo.addItem(layer.name(), layer.id())

        # Try to restore previous selection
        if current_vocab:
            index = self.vocab_layer_combo.findData(current_vocab)
            if index >= 0:
                self.vocab_layer_combo.setCurrentIndex(index)

        if current_feature:
            index = self.feature_layer_combo.findData(current_feature)
            if index >= 0:
                self.feature_layer_combo.setCurrentIndex(index)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = qskosDialog()

            # Get references to UI widgets
            self.load_rdf_button = self.dlg.findChild(QAction, 'loadRdfButton')
            self.load_csv_button = self.dlg.findChild(QAction, 'loadCsvButton')
            self.vocab_layer_combo = self.dlg.findChild(QComboBox, 'vocabLayerCombo')
            self.feature_layer_combo = self.dlg.findChild(QComboBox, 'featureLayerCombo')
            self.bind_button = self.dlg.findChild(QPushButton, 'bindButton')
            self.tree_widget = self.dlg.findChild(QTreeWidget, 'conceptTreeWidget')

            # Set up the tree widget
            self.tree_widget.setHeaderLabels(["Concept", "URI"])
            self.tree_widget.setColumnCount(2)
            self.tree_widget.setColumnHidden(1, True) # Hide URI column

            # Connect signals
            self.dlg.loadRdfButton.clicked.connect(self.load_rdf_vocabulary)
            self.dlg.loadCsvButton.clicked.connect(self.load_csv_vocabulary)
            self.bind_button.clicked.connect(self.bind_layers)
            self.feature_layer_combo.currentIndexChanged.connect(self.on_feature_layer_changed)
            self.vocab_layer_combo.currentIndexChanged.connect(self.on_vocab_layer_changed)

            # Initial refresh
            self.refresh_layer_dropdowns()

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass

    def load_rdf_vocabulary(self):
        """Loads an RDF file or URL and converts it to a delimited text layer."""
        source, ok = QFileDialog.getOpenFileName(
            self.dlg,
            self.tr("Select RDF File"),
            "",
            self.tr("RDF Files (*.ttl *.jsonld);;All Files (*)")
        )

        if not ok or not source:
            return

        try:
            graph = Graph()
            if source.startswith(('http://', 'https://')):
                # Load from URL
                with urllib.request.urlopen(source) as response:
                    data = response.read()
                    if source.endswith('.jsonld'):
                        graph.parse(data=data, format='json-ld')
                    else:
                        # Assume Turtle for URLs if not .jsonld
                        graph.parse(data=data, format='turtle')
            else:
                # Load from local file
                if source.endswith('.jsonld'):
                    graph.parse(source, format='json-ld')
                else:
                    graph.parse(source, format='turtle')

            # Extract ConceptScheme URI
            scheme_uri = None
            for s, p, o in graph.triples((None, RDF.type, SKOS.ConceptScheme)):
                scheme_uri = str(s)
                break

            if not scheme_uri:
                # If no ConceptScheme found, use the first concept's scheme
                for s, p, o in graph.triples((None, SKOS.inScheme, None)):
                    scheme_uri = str(o)
                    break

            if not scheme_uri:
                scheme_uri = "http://example.org/unknown-scheme"

            # Prepare CSV data
            csv_rows = []
            for concept in graph.subjects(RDF.type, SKOS.Concept):
                concept_uri = str(concept)

                # Get prefLabels
                pref_labels = {}
                for label in graph.objects(concept, SKOS.prefLabel):
                    if isinstance(label, Literal) and label.language:
                        pref_labels[label.language] = label.value
                    elif isinstance(label, Literal):
                        pref_labels[''] = label.value

                # Format prefLabel for CSV: "label@lang|label2@lang2"
                pref_label_str = "|".join([f"{v}@{k}" if k else v for k, v in pref_labels.items()])

                # Get definitions
                definitions = {}
                for definition in graph.objects(concept, SKOS.definition):
                    if isinstance(definition, Literal) and definition.language:
                        definitions[definition.language] = definition.value
                    elif isinstance(definition, Literal):
                        definitions[''] = definition.value

                definition_str = "|".join([f"{v}@{k}" if k else v for k, v in definitions.items()])

                # Get broader
                broader_uri = ""
                for broader in graph.objects(concept, SKOS.broader):
                    broader_uri = str(broader)
                    break # Only take the first for simplicity

                # Get inScheme
                in_scheme_uri = scheme_uri # Default to scheme
                for scheme in graph.objects(concept, SKOS.inScheme):
                    in_scheme_uri = str(scheme)
                    break

                csv_rows.append({
                    'skos:Concept': concept_uri,
                    'skos:prefLabel': pref_label_str,
                    'skos:definition': definition_str,
                    'skos:broader': broader_uri,
                    'skos:inScheme': in_scheme_uri
                })

            # Write to temporary CSV file
            temp_csv = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', encoding='utf-8', newline='')
            fieldnames = ['skos:Concept', 'skos:prefLabel', 'skos:definition', 'skos:broader', 'skos:inScheme']
            writer = csv.DictWriter(temp_csv, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            writer.writerows(csv_rows)
            temp_csv.close()

            # Create delimited text layer URI
            uri = f"file:///{temp_csv.name}?type=csv&noGeometry=yes&crs=EPSG:4326&trimFields=yes&detectTypes=yes"

            # Create layer
            layer_name = scheme_uri
            vocab_layer = QgsVectorLayer(uri, layer_name, "delimitedtext")

            if not vocab_layer.isValid():
                QMessageBox.critical(self.dlg, "Error", "Failed to load the vocabulary layer.")
                os.unlink(temp_csv.name)
                return

            # Set custom property
            vocab_layer.setCustomProperty("qskos:scheme", scheme_uri)

            # Add to project
            QgsProject.instance().addMapLayer(vocab_layer)

            # Inform user
            self.iface.messageBar().pushMessage(
                "Success",
                f"Vocabulary '{layer_name}' loaded successfully.",
                level=Qgis.Success,
                duration=5
            )

        except Exception as e:
            QMessageBox.critical(self.dlg, "Error", f"Failed to load RDF: {str(e)}")
            QgsMessageLog.logMessage(f"RDF Load Error: {str(e)}", 'qskos', Qgis.Critical)

    def load_csv_vocabulary(self):
        """Loads a CSV file and converts it to a delimited text layer."""
        source, ok = QFileDialog.getOpenFileName(
            self.dlg,
            self.tr("Select CSV File"),
            "",
            self.tr("CSV Files (*.csv);;All Files (*)")
        )

        if not ok or not source:
            return

        try:
            # Read the CSV to find the concept scheme
            scheme_uri = None
            with open(source, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row.get('skos:inScheme'):
                        scheme_uri = row['skos:inScheme']
                        break

            if not scheme_uri:
                scheme_uri = "http://example.org/unknown-scheme-from-csv"

            # Create delimited text layer URI
            # We use the original file, no need to create a temp copy for CSV
            uri = f"file:///{source}?type=csv&noGeometry=yes&crs=EPSG:4326&trimFields=yes&detectTypes=yes"

            # Create layer
            layer_name = scheme_uri
            vocab_layer = QgsVectorLayer(uri, layer_name, "delimitedtext")

            if not vocab_layer.isValid():
                QMessageBox.critical(self.dlg, "Error", "Failed to load the CSV vocabulary layer.")
                return

            # Set custom property
            vocab_layer.setCustomProperty("qskos:scheme", scheme_uri)

            # Add to project
            QgsProject.instance().addMapLayer(vocab_layer)

            # Inform user
            self.iface.messageBar().pushMessage(
                "Success",
                f"Vocabulary '{layer_name}' loaded successfully.",
                level=Qgis.Success,
                duration=5
            )

        except Exception as e:
            QMessageBox.critical(self.dlg, "Error", f"Failed to load CSV: {str(e)}")
            QgsMessageLog.logMessage(f"CSV Load Error: {str(e)}", 'qskos', Qgis.Critical)

    def bind_layers(self):
        """Binds the selected feature layer to the selected vocabulary layer."""
        feature_layer_id = self.feature_layer_combo.currentData()
        vocab_layer_id = self.vocab_layer_combo.currentData()

        if not feature_layer_id or not vocab_layer_id:
            QMessageBox.warning(self.dlg, "Warning", "Please select both a feature layer and a vocabulary layer.")
            return

        feature_layer = QgsProject.instance().mapLayer(feature_layer_id)
        vocab_layer = QgsProject.instance().mapLayer(vocab_layer_id)

        if not feature_layer or not vocab_layer:
            QMessageBox.critical(self.dlg, "Error", "Selected layers are invalid.")
            return

        # Get scheme URI from vocab layer
        scheme_uri = vocab_layer.customProperty("qskos:scheme")
        if not scheme_uri:
            QMessageBox.critical(self.dlg, "Error", "The selected vocabulary layer is not valid (missing qskos:scheme).")
            return

        # Set binding on feature layer
        feature_layer.setCustomProperty("qskos:binding", scheme_uri)

        # Update UI
        self.on_feature_layer_changed()

        self.iface.messageBar().pushMessage(
            "Success",
            f"Layer '{feature_layer.name()}' bound to vocabulary '{vocab_layer.name()}'.",
            level=Qgis.Success,
            duration=5
        )

    def on_feature_layer_changed(self):
        """Called when the feature layer selection changes. Updates the tree view."""
        self.tree_widget.clear()
        feature_layer_id = self.feature_layer_combo.currentData()
        if not feature_layer_id:
            return

        feature_layer = QgsProject.instance().mapLayer(feature_layer_id)
        if not feature_layer:
            return

        # Get bound scheme URI
        bound_scheme_uri = feature_layer.customProperty("qskos:binding")
        if not bound_scheme_uri:
            return

        # Find the bound vocabulary layer
        vocab_layer = None
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer and \
               layer.dataProvider().name() == 'delimitedtext' and \
               layer.customProperty('qskos:scheme') == bound_scheme_uri:
                vocab_layer = layer
                break

        if not vocab_layer:
            return

        # Build hierarchy
        concepts = {}
        root_items = []

        # First pass: create all items
        for feature in vocab_layer.getFeatures():
            uri = feature['skos:Concept']
            broader_uri = feature['skos:broader']
            label = self._get_preferred_label(feature['skos:prefLabel'])

            item = QTreeWidgetItem([label, uri])
            checkbox = QCheckBox()
            checkbox.stateChanged.connect(lambda state, u=uri: self.on_concept_checked(u, state))
            self.tree_widget.setItemWidget(item, 0, checkbox)

            # Check if field already exists
            for field in feature_layer.fields():
                if field.name() == uri:
                    checkbox.setChecked(True)
                    break

            concepts[uri] = {
                'item': item,
                'broader': broader_uri,
                'children': []
            }

        # Second pass: build tree structure
        for uri, data in concepts.items():
            broader_uri = data['broader']
            if broader_uri and broader_uri in concepts:
                concepts[broader_uri]['children'].append(data['item'])
            else:
                root_items.append(data['item'])

        # Add root items to tree
        self.tree_widget.addTopLevelItems(root_items)

        # Expand all items
        self.tree_widget.expandAll()

    def _get_preferred_label(self, pref_label_str):
        """Extracts the preferred label, preferring German, then English, then first available."""
        if not pref_label_str:
            return ""

        labels = {}
        parts = pref_label_str.split('|')
        for part in parts:
            if '@' in part:
                value, lang = part.rsplit('@', 1)
                labels[lang] = value
            else:
                labels[''] = part

        # Return German, then English, then any other
        if 'de' in labels:
            return labels['de']
        elif 'en' in labels:
            return labels['en']
        elif labels:
            return next(iter(labels.values()))
        else:
            return ""

    def on_vocab_layer_changed(self):
        """Called when the vocabulary layer selection changes. Currently a no-op."""
        pass

    def on_concept_checked(self, concept_uri, state):
        """Called when a concept's checkbox is checked or unchecked."""
        feature_layer_id = self.feature_layer_combo.currentData()
        if not feature_layer_id:
            return

        feature_layer = QgsProject.instance().mapLayer(feature_layer_id)
        if not feature_layer:
            return

        # Get bound scheme URI
        bound_scheme_uri = feature_layer.customProperty("qskos:binding")
        if not bound_scheme_uri:
            return

        # Find the bound vocabulary layer
        vocab_layer = None
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer and \
               layer.dataProvider().name() == 'delimitedtext' and \
               layer.customProperty('qskos:scheme') == bound_scheme_uri:
                vocab_layer = layer
                break

        if not vocab_layer:
            return

        if state == Qt.Checked:
            # Create the field
            self._create_annotation_field(feature_layer, concept_uri, vocab_layer)
        else:
            # Remove the field (optional, as per spec it only says what happens on check)
            # We'll leave it for now, as removing fields from a layer is complex and can cause data loss.
            pass

    def _create_annotation_field(self, feature_layer, concept_uri, vocab_layer):
        """Creates an annotation field for the given concept URI."""
        # Check if field already exists
        for field in feature_layer.fields():
            if field.name() == concept_uri:
                return # Already exists

        # Get concept label for alias
        label = ""
        for feat in vocab_layer.getFeatures(f""""skos:Concept" = '{concept_uri.replace("'", "''")}'"""):
            label = self._get_preferred_label(feat['skos:prefLabel'])
            break

        # Start editing the layer
        if not feature_layer.isEditable():
            if not feature_layer.startEditing():
                QMessageBox.critical(self.dlg, "Error", "Could not start editing the layer.")
                return

        # Add field
        new_field = QgsField(concept_uri, 10) # 10 is QVariant.Map (JSON)
        if feature_layer.addAttribute(new_field):
            feature_layer.updateFields()
            # Set field alias
            field_index = feature_layer.fields().indexOf(concept_uri)
            feature_layer.addAttributeAlias(field_index, label)

            # Configure Value Relation widget
            self._configure_value_relation_widget(feature_layer, field_index, concept_uri, vocab_layer)

            # Commit changes
            if not feature_layer.commitChanges():
                QMessageBox.warning(self.dlg, "Warning", "Failed to commit changes to layer.")
        else:
            feature_layer.rollBack()
            QMessageBox.critical(self.dlg, "Error", "Failed to add the new field.")

    def _configure_value_relation_widget(self, feature_layer, field_index, root_concept_uri, vocab_layer):
        """Configures the Value Relation widget for the field."""
        # Get all descendant URIs
        descendant_uris = self._get_descendant_uris(root_concept_uri, vocab_layer)

        # Build filter expression
        if descendant_uris:
            uri_list = "', '".join([uri.replace("'", "''") for uri in descendant_uris])
            filter_expr = f""""skos:Concept" IN ('{uri_list}')"""
        else:
            filter_expr = f""""skos:Concept" = '{root_concept_uri.replace("'", "''")}'"""

        # Get the layer's editor widget setup
        setup = feature_layer.editorWidgetSetup(field_index)

        # Create Value Relation config
        config = {
            'Layer': vocab_layer.id(),
            'Key': 'skos:Concept',
            'Value': 'skos:prefLabel',
            'Description': 'skos:definition',
            'FilterExpression': filter_expr,
            'AllowMulti': True,
            'UseCompleter': True,
            'OrderByValue': False,
            'AllowNull': True
        }

        from qgis.gui import QgsEditorWidgetSetup
        new_setup = QgsEditorWidgetSetup('ValueRelation', config)
        feature_layer.setEditorWidgetSetup(field_index, new_setup)

    def _get_descendant_uris(self, root_uri, vocab_layer):
        """Recursively gets all descendant URIs for a given root concept."""
        descendants = [root_uri]

        def find_children(parent_uri):
            children = []
            expr = f""""skos:broader" = '{parent_uri.replace("'", "''")}'"""
            for feat in vocab_layer.getFeatures(QgsExpression(expr)):
                child_uri = feat['skos:Concept']
                children.append(child_uri)
                descendants.append(child_uri)
                # Recurse
                grandchildren = find_children(child_uri)
                children.extend(grandchildren)
            return children

        find_children(root_uri)
        return descendants